### ISSUE TITLE
Interested in `hrtf` for a non-rg3d project - any interest in splitting it into a separate crate?

### ISSUE THREAD

**Issue by mitchmindtree** [mrDIMAS/rg3d-sound#5]
Hey there! I've been doing a bit of investigating into what's available w.r.t. binaural audio in Rust. I have an existing project using [nannou](https://nannou.cc/), but would love to take advantage of this `hrtf` work.

Is there any chance you would be interested in splitting the `hrtf` module into its own independent crate? I can imagine there would be a lot of interest in collaboration / co-maintaining from other pro-audio / creative-coder / gamedev folks out there too :)

**Comment by mrDIMAS** [comment]
Hello! I thought about this when I was impementing HRTF in the engine, I tried to make `hrtf` module to be as independent as possible so it should be easy to extract it and put into separate crate. I'll try to extract it as soon as possible, I hope it will be useful!

**Comment by mrDIMAS** [comment]
Here you go - https://crates.io/crates/hrtf or https://github.com/mrDIMAS/hrtf

**Comment by mitchmindtree** [comment]
Awesome, thanks so much!
