### ISSUE TITLE
Explicitly versioning rg3d-core

### ISSUE THREAD

**Issue by darbaga** [mrDIMAS/rg3d-sound#6]
Hello,

Right now rg3d-core in cargo.toml is using a relative path. It would be very useful to make this use an actual version-I want to use this in a game that isn't using the rg3d engine but nevertheless would love to have the sound capabilities of this crate.

**Comment by mrDIMAS** [comment]
Hi, what is the problem to git clone rg3d-core near your project? The problem with explicit versioning that is will significantly complicate development on my side, because I'd need to use [patch] section in Cargo.toml to override dependency.

**Comment by darbaga** [comment]
Hi, there isn't a problem exactly-it's just surprising because the traditional workflow in usual Rust projects is to just add a crate in cargo.toml. If it complicates development too much though, it's probably fine as is.

Relatedly, though, I would at least advise adding the requirement in the readme. Right now the only way you find out is cloning rg3d-sound and reading cargo.toml-it would probably be easier to have that explicitly spelled out in the Readme itself.

**Comment by mrDIMAS** [comment]
Actually, I think I'll move rg3d-sound (and other deps) in rg3d repo soon and will make workspace there. You still be able to use crates.io version.
